version: '3.1'

services:
  # Database
  db: 
    image: mysql:5.7
    container_name: backend_mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  
  #phmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: backend_phpmyadmin
    restart: always
    ports: 
      - '8090:80'
    environment:
      PMP_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite
  
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: backend_wordpess
    ports:
      - 8000:80
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite
networks:
  wpsite: 
volumes:
  db_data: